enableGlobalCache: false

packageExtensions:
  "@joshwooding/vite-plugin-react-docgen-typescript@*":
    dependencies:
      vite: "*"
  "@storybook/builder-vite@*":
    dependencies:
      vite: "*"
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "*"
  "@storybook/react-dom-shim@*":
    dependencies:
      react: "*"
      react-dom: "*"
  chalk@*:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  "@babel/core@*":
    dependencies:
      "next": "*"
      "@linaria/babel-preset": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-since.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-workspace-since/160d5c3/bundles/%40yarnpkg/plugin-workspace-since.js"

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-3.6.0.cjs
